# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

def shared_pods
    source 'https://github.com/CocoaPods/Specs'
    use_frameworks!
        pod 'BEMCheckBox', '~> 1.4.1'
end

target 'DBAttachmentPickerControllerExample' do
    shared_pods
end

